image_finetune: false

output_dir: "./experiments"
pretrained_model_path: "models/StableDiffusion/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_inflated_groupnorm:     true # v2: without this line
  use_motion_module:          true
  motion_module_resolutions:  [1,2,4,8]
  motion_module_mid_block:    false # v2: true
  motion_module_type:         Vanilla

  motion_module_kwargs:
    num_attention_heads:                 8
    num_transformer_block:               1
    attention_block_types:               [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding:          true
    temporal_position_encoding_max_len:  32
    temporal_attention_dim_div:          1
    zero_initialize:                     true


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  target: motionctrl.data.realestate10k.RealEstate10K # camera pose only # 62992L
  params:
    data_dir: datasets/RealEstate10K/process/train
    meta_path: datasets/RealEstate10K/caption/train
    meta_list: /datasets/RealEstate10K/caption/train.txt
    video_length: 16
    frame_stride: [1,10]
    resolution: [512,512]
    spatial_transform: resize_center_crop
    invert_video: true
    RT_norm: true
  sample_size: 512
  sample_n_frames: 16

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "close up photo of a rabbit, forest, haze, halation, bloom, dramatic atmosphere, centred, rule of thirds, 200mm 1.4f macro shot"
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "close up photo of a rabbit, forest, haze, halation, bloom, dramatic atmosphere, centred, rule of thirds, 200mm 1.4f macro shot"
  RT_paths:
    - /group/30098/zhouxiawang/outputs/LDVMPose/examples/cus_camera_motion/test_camera_SPIN-ACW.json
    - /group/30098/zhouxiawang/outputs/LDVMPose/examples/cus_camera_motion/test_camera_SPIN-CW.json
    - /group/30098/zhouxiawang/outputs/LDVMPose/examples/cus_camera_motion/test_camera_I_2.0x.json
    - /group/30098/zhouxiawang/outputs/LDVMPose/examples/cus_camera_motion/test_camera_Round-RI-120.json
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules: ~

unet_checkpoint_path: "models/Motion_Module/v3_sd15_mm.ckpt"

learning_rate:    1.e-5
train_batch_size: 1
gradient_accumulation_steps: 4

max_train_epoch:      -1
max_train_steps:      1000000
checkpointing_epochs: -1
checkpointing_steps:  1000

validation_steps:       1000
validation_steps_tuple: [2, 50, 500]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: false

cmcm_checkpoint_path: ~
enable_cmcm: true
enable_omcm: false
appearance_debias: 5