- inference_config: configs/inference/inference-v3.yaml
  motion_module: models/Motion_Module/v3_sd15_mm.ckpt
  cmcm_checkpoint_path: models/MotionCtrl/motionctrl_animatediff_cmcm.ckpt
  lora_model_path: ''
  seed:
  - 3638500841
  - 16046708080676731040
  - 16403310442494881856
  - 12859041357761502239
  - 13897214542379912903
  steps: 25
  guidance_scale: 7.5
  prompt:
  - intricate detailing,photorealism,hyperrealistic, glowing jellyfish mushroom, flying,
    starry sky, bokeh, golden ratio composition,
  - Detailed craftsmanship, photorealism, hyperrealistic, roaring waterfall, misty
    spray, lush greenery, vibrant rainbow, golden ratio composition.
  - Exquisite detail depiction, photo-realistic sensation, surrealism, ancient castles,
    towering towers, sprawling ivy, traces of history, golden ratio composition.
  - Intricate detailing, photorealism, hyperrealistic, blooming cherry blossom, fluttering
    petals, soft sunlight, serene park, golden ratio composition.
  n_prompt:
  - FastNegativeV2,(bad-artist:1),(worst quality, low quality:1.4),(bad_prompt_version2:0.8),bad-hands-5,lowres,bad
    anatomy,bad hands,((text)),(watermark),error,missing fingers,extra digit,fewer
    digits,cropped,worst quality,low quality,normal quality,((username)),blurry,(extra
    limbs),bad-artist-anime,badhandv4,EasyNegative,ng_deepnegative_v1_75t,verybadimagenegative_v1.3,BadDream,(three
    hands:1.6),(three legs:1.2),(more than two hands:1.4),(more than two legs,:1.2),
  RT_paths:
  - examples/camera_poses/test_camera_d971457c81bca597.json
  - examples/camera_poses/test_camera_R_1.0x.json
  - examples/camera_poses/test_camera_R_2.0x.json
  - examples/camera_poses/test_camera_SPIN-LR.json
  W: 512
  H: 512
  L: 16
  random_seed:
  - 3638500841
  - 16046708080676731040
  - 16403310442494881856
  - 12859041357761502239
  - 3638500841
  - 16046708080676731040
  - 16403310442494881856
  - 12859041357761502239
  - 3638500841
  - 16046708080676731040
  - 16403310442494881856
  - 12859041357761502239
  - 3638500841
  - 16046708080676731040
  - 16403310442494881856
  - 12859041357761502239
