- inference_config: "configs/inference/inference-v3.yaml"
  motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"
  cmcm_checkpoint_path: "models/MotionCtrl/motionctrl_animatediff_cmcm.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors"

  lora_model_path: ""

  seed:           [9329399085567825781, 16987697414827649302]
  steps:          25
  guidance_scale: 7.5


  prompt: 
    - "photo of coastline, rocks, storm weather, wind, waves, lightning, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
    - "night, b&w photo of old house, post apocalypse, forest, storm weather, wind, rocks, 8k uhd, dslr, soft lighting, high quality, film grain"
  n_prompt:
    - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
    - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, art, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation"
  RT_paths:
    - "examples/camera_poses/test_camera_d971457c81bca597.json"
    - "examples/camera_poses/test_camera_R_1.0x.json"
    - "examples/camera_poses/test_camera_R_2.0x.json"
    # - "examples/camera_poses/test_camera_Round-ZoomIn.json"
    # - "examples/camera_poses/test_camera_SPIN-DU.json"
    - "examples/camera_poses/test_camera_SPIN-LR.json"